allowBuilds:
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@tanstack/react-router@1.170.41'
  - '@tanstack/router-core@1.171.34'
  - '@tanstack/router-generator@1.167.40'
  - '@tanstack/router-plugin@1.168.42'
overrides:
  brace-expansion@<1.1.19: ^1.1.19
  brace-expansion@<1.1.20: ^1.1.20
  brace-expansion@<1.1.21: ^1.1.21
  brace-expansion@>=4.0.0 <5.0.10: ^5.0.10
  brace-expansion@>=4.0.0 <5.0.11: ^5.0.11
  brace-expansion@>=4.0.0 <5.0.12: ^5.0.12
  jsondiffpatch@<0.7.2: ^0.7.2
  jsondiffpatch@<0.7.6: ^0.7.6
