version = "3.11.5"
runner.dialect = scala3

align.preset = most
maxColumn = 120

rewrite.trailingCommas.style = "keep"
rewrite.scala3.convertToNewSyntax = true
rewrite.rules = [Imports]
rewrite.imports.sort = scalastyle
rewrite.imports.groups = [["java\\..*"], ["scala\\..*"], ["dotty\\..*"]]

newlines.source = keep
newlines.implicitParamListModifierPrefer = before

docstrings.style = Asterisk
