# This runs a dev-local environment by building the frontend + backend,
# and serving them locally behind Caddy on localhost:80 (no hot-reloading)
#
# If you require a frontend dev-server with hot-reloading, copy the relevant
# section from docker-compose.override.examples.yml -> docker-compose.override.yml
include:
  - ./docker/backend.yml
  - ./docker/proxy.yml
