http {
  interface: 0.0.0.0
  port: 10000
}
database: {
  url = "jdbc:postgresql://db:5432/hosts"
  user = "postgres"
  password = "postgres"
}
pekko {
  loggers = [org.apache.pekko.event.slf4j.Slf4jLogger]
  loglevel = DEBUG
  logging-filter = org.apache.pekko.event.slf4j.Slf4jLoggingFilter
  http.server {
    remote-address-header = true
    websocket.periodic-keep-alive-max-idle = 5 second
  }
}
reddit {
  clientId = ""
  clientSecret = ""
  redirectUri = ""
  queueSize = 10
}
session {
  idleTimeout = 8 days
  absoluteTimeout = 90 days
  rotateInterval = 1 day
  sweepInterval = 15 minutes
}
disable instrumentation = true
