services:
  caddy:
    build:
      context: ..
      dockerfile: ./caddy/local/Dockerfile
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c", "exec caddy run --config /etc/caddy/Caddyfile --adapter caddyfile"]
    command: []
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
