import type { Dayjs } from '../dayjs';

export type Match = {
  id: number;
  author: string;
  opens: Dayjs;
  address: string | null;
  ip: string | null;
  scenarios: string[];
  tags: string[];
  teams: string;
  size: number | null;
  customStyle: string | null;
  count: number;
  content: string;
  region: string;
  removed: boolean;
  removedAt: Dayjs | null;
  removedBy: string | null;
  removedReason: string | null;
  created: Dayjs;
  location: string;
  mainVersion: string;
  version: string;
  slots: number;
  length: number;
  mapSize: number;
  pvpEnabledAt: number;
  approvedBy: string | null;
  hostingName: string | null;
  tournament: boolean;
  roles: Array<string>;
};
