/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembersRouteImport } from './routes/members'
import { Route as AuthenticatedHostRouteImport } from './routes/_authenticated.host'
import { Route as AuthenticatedModifiersRouteImport } from './routes/_authenticated.modifiers'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedQuizRouteImport } from './routes/_authenticated.quiz'
import { Route as HostApplicationsIndexRouteImport } from './routes/host-applications/index'
import { Route as MIdRouteImport } from './routes/m.$id'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as MatchesHostRouteImport } from './routes/matches/$host'
import { Route as AuthenticatedHostApplicationsApplyRouteImport } from './routes/_authenticated.host-applications.apply'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHostRoute = AuthenticatedHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModifiersRoute = AuthenticatedModifiersRouteImport.update({
  id: '/modifiers',
  path: '/modifiers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizRoute = AuthenticatedQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const HostApplicationsIndexRoute = HostApplicationsIndexRouteImport.update({
  id: '/host-applications/',
  path: '/host-applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const MIdRoute = MIdRouteImport.update({
  id: '/m/$id',
  path: '/m/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesHostRoute = MatchesHostRouteImport.update({
  id: '/matches/$host',
  path: '/matches/$host',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHostApplicationsApplyRoute =
  AuthenticatedHostApplicationsApplyRouteImport.update({
    id: '/host-applications/apply',
    path: '/host-applications/apply',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/host': typeof AuthenticatedHostRoute
  '/modifiers': typeof AuthenticatedModifiersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/m/$id': typeof MIdRoute
  '/matches/$host': typeof MatchesHostRoute
  '/host-applications/': typeof HostApplicationsIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/host-applications/apply': typeof AuthenticatedHostApplicationsApplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/host': typeof AuthenticatedHostRoute
  '/modifiers': typeof AuthenticatedModifiersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/m/$id': typeof MIdRoute
  '/matches/$host': typeof MatchesHostRoute
  '/host-applications': typeof HostApplicationsIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/host-applications/apply': typeof AuthenticatedHostApplicationsApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/_authenticated/host': typeof AuthenticatedHostRoute
  '/_authenticated/modifiers': typeof AuthenticatedModifiersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/quiz': typeof AuthenticatedQuizRoute
  '/m/$id': typeof MIdRoute
  '/matches/$host': typeof MatchesHostRoute
  '/host-applications/': typeof HostApplicationsIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/_authenticated/host-applications/apply': typeof AuthenticatedHostApplicationsApplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/members'
    | '/host'
    | '/modifiers'
    | '/profile'
    | '/quiz'
    | '/m/$id'
    | '/matches/$host'
    | '/host-applications/'
    | '/matches/'
    | '/host-applications/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/members'
    | '/host'
    | '/modifiers'
    | '/profile'
    | '/quiz'
    | '/m/$id'
    | '/matches/$host'
    | '/host-applications'
    | '/matches'
    | '/host-applications/apply'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/members'
    | '/_authenticated/host'
    | '/_authenticated/modifiers'
    | '/_authenticated/profile'
    | '/_authenticated/quiz'
    | '/m/$id'
    | '/matches/$host'
    | '/host-applications/'
    | '/matches/'
    | '/_authenticated/host-applications/apply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  MIdRoute: typeof MIdRoute
  MatchesHostRoute: typeof MatchesHostRoute
  HostApplicationsIndexRoute: typeof HostApplicationsIndexRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/host': {
      id: '/_authenticated/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof AuthenticatedHostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/modifiers': {
      id: '/_authenticated/modifiers'
      path: '/modifiers'
      fullPath: '/modifiers'
      preLoaderRoute: typeof AuthenticatedModifiersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz': {
      id: '/_authenticated/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthenticatedQuizRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/host-applications/': {
      id: '/host-applications/'
      path: '/host-applications'
      fullPath: '/host-applications/'
      preLoaderRoute: typeof HostApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$id': {
      id: '/m/$id'
      path: '/m/$id'
      fullPath: '/m/$id'
      preLoaderRoute: typeof MIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$host': {
      id: '/matches/$host'
      path: '/matches/$host'
      fullPath: '/matches/$host'
      preLoaderRoute: typeof MatchesHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/host-applications/apply': {
      id: '/_authenticated/host-applications/apply'
      path: '/host-applications/apply'
      fullPath: '/host-applications/apply'
      preLoaderRoute: typeof AuthenticatedHostApplicationsApplyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHostRoute: typeof AuthenticatedHostRoute
  AuthenticatedModifiersRoute: typeof AuthenticatedModifiersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuizRoute: typeof AuthenticatedQuizRoute
  AuthenticatedHostApplicationsApplyRoute: typeof AuthenticatedHostApplicationsApplyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHostRoute: AuthenticatedHostRoute,
  AuthenticatedModifiersRoute: AuthenticatedModifiersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuizRoute: AuthenticatedQuizRoute,
  AuthenticatedHostApplicationsApplyRoute:
    AuthenticatedHostApplicationsApplyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  MIdRoute: MIdRoute,
  MatchesHostRoute: MatchesHostRoute,
  HostApplicationsIndexRoute: HostApplicationsIndexRoute,
  MatchesIndexRoute: MatchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
