CREATE TABLE ubl (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  ign TEXT NOT NULL,
  uuid UUID NOT NULL,
  reason TEXT NOT NULL,
  created TIMESTAMP NOT NULL,
  expires TIMESTAMP NOT NULL,
  link TEXT NOT NULL
);