ALTER TABLE matches ADD COLUMN location TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE matches ALTER COLUMN location DROP DEFAULT;

ALTER TABLE matches ADD COLUMN version TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE matches ALTER COLUMN version DROP DEFAULT;

ALTER TABLE matches ADD COLUMN slots INT NOT NULL DEFAULT 100;
ALTER TABLE matches ALTER COLUMN slots DROP DEFAULT;

ALTER TABLE matches ADD COLUMN length INT NOT NULL DEFAULT 90;
ALTER TABLE matches ALTER COLUMN length DROP DEFAULT;

ALTER TABLE matches ADD COLUMN mapSizeX INT NOT NULL DEFAULT 1500;
ALTER TABLE matches ALTER COLUMN mapSizeX DROP DEFAULT;

ALTER TABLE matches ADD COLUMN mapSizeZ INT NOT NULL DEFAULT 1500;
ALTER TABLE matches ALTER COLUMN mapSizeZ DROP DEFAULT;

ALTER TABLE matches ADD COLUMN pvpEnabledAt INT NOT NULL DEFAULT 20;
ALTER TABLE matches ALTER COLUMN pvpEnabledAt DROP DEFAULT;